---

- name: Install apache httpd and mod_wsgi
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - mod_wsgi


- name: Set listen port
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen " line="Listen {{ graphite_httpport }}"
  notify:
    - reload httpd

- name: Add graphite vhost
  template: src=etc/httpd/conf.d/graphite.conf.j2 dest=/etc/httpd/conf.d/graphite.conf
   owner=apache group=apache mode=0644
  notify:
    - reload httpd
